/**
 * Ground truth das amostras enviadas (02/08/2026) — para calibrar o extrator.
 * NÃO inclui as imagens (PII). Usar só em teste local.
 */
export const DOCUMENT_SAMPLE_EXPECTATIONS = [
  {
    id: "amanda-rg-cpf",
    types: ["RG", "CPF"],
    fullName: "AMANDA RIBEIRO SOARES",
    birthDateBR: "19/04/1998",
    cpf: "12652206460",
    gender: null as "M" | "F" | null,
    notes: "CPF no comprovante; no RG verso pode estar ilegível sob assinatura",
  },
  {
    id: "islany-cnh-digital",
    types: ["CNH"],
    fullName: "ISLANY DE LIMA MEDEIROS",
    birthDateBR: "14/01/1997",
    cpf: "12381352422",
    gender: null,
  },
  {
    id: "josemar-rg-verso",
    types: ["RG"],
    fullName: "JOSEMAR AGOSTINHO DA SILVA",
    birthDateBR: "06/02/1988",
    cpf: "41627127860",
    gender: null,
  },
  {
    id: "kléssia-cin",
    types: ["CIN"],
    fullName: "KLÉSSIA SILVA SIMÕES",
    birthDateBR: "25/11/1992",
    cpf: "01707044406",
    gender: "F" as const,
  },
  {
    id: "suesvanio-cnh",
    types: ["CNH"],
    fullName: "SUESVANIO VILAR CAMILO",
    birthDateBR: "07/06/1994",
    cpf: "11322587400",
    gender: null,
  },
  {
    id: "livya-certidao",
    types: ["CERTIDAO"],
    fullName: "LIVYA VITORIA SILVA DOS SANTOS",
    birthDateBR: "06/09/2021",
    cpf: "17823271427",
    gender: "F" as const,
  },
  {
    id: "marinalva-rg",
    types: ["RG"],
    fullName: "MARINALVA SOARES DA SILVA",
    birthDateBR: "08/10/1977",
    cpf: null,
    gender: null,
    notes: "Frente sem CPF visível",
  },
  {
    id: "iann-cin",
    types: ["CIN"],
    fullName: "IANN KEVIN SANTANA DE FREITAS",
    birthDateBR: "11/02/2013",
    cpf: "07845411590",
    gender: "M" as const,
  },
  {
    id: "alessandro-cin",
    types: ["CIN"],
    fullName: "ALESSANDRO ROGERIO SANTOS DE FREITAS",
    birthDateBR: "24/12/1975",
    cpf: "90787501549",
    gender: "M" as const,
  },
  {
    id: "izabelly-rg",
    types: ["RG"],
    fullName: "IZABELLY GOMES DE SOUSA",
    birthDateBR: "15/08/2017",
    cpf: null,
    gender: null,
  },
  {
    id: "jucileide-rg",
    types: ["RG"],
    fullName: "JUCILEIDE DE SOUSA PEREIRA",
    birthDateBR: "15/06/1983",
    cpf: null,
    gender: null,
  },
  {
    id: "isadora-cin-bebe",
    types: ["CIN"],
    fullName: "ISADORA SILVA ARAÚJO",
    birthDateBR: "30/06/2024",
    cpf: "04169662091",
    gender: "F" as const,
  },
  {
    id: "antonio-cnh",
    types: ["CNH"],
    fullName: "ANTONIO LOPES DE ARAUJO",
    birthDateBR: "06/05/1970",
    cpf: "72796570444",
    gender: null,
  },
  {
    id: "erica-rg",
    types: ["RG"],
    fullName: "ÉRICA MARIA DE MEDEIROS",
    birthDateBR: "08/03/1991",
    cpf: "08686768458",
    gender: null,
  },
  {
    id: "jose-denys-rg",
    types: ["RG"],
    fullName: "JOSÉ DENYS MEDEIRO ARAUJO",
    birthDateBR: "03/08/2014",
    cpf: "04659613046",
    gender: null,
  },
] as const;
